sudo: required
services:
  - docker

before_install:
  - docker build -t tg5688/multicontainer-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tg5688/multicontainer-test npm run test

after_success:
  - docker build -t tg5688/multicontainer-client ./client
  - docker build -t tg5688/multicontainer-nginx ./nginx
  - docker build -t tg5688/multicontainer-server ./server
  - docker build -t tg5688/multicontainer-worker ./worker

  #log in tothe docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images ang push them to docker hub
  - docker push tg5688/multicontainer-client 
  - docker push tg5688/multicontainer-nginx 
  - docker push tg5688/multicontainer-server 
  - docker push tg5688/multicontainer-worker 

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-070379457966"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
